version: '3.5'

services:
  php:
    container_name: php
    build:
      context: ./docker/php
      args:
        TIMEZONE: Asia/Tokyo
    volumes:
      - .:/var/www/php-enum
    working_dir: /var/www/php-enum
    command: >
      bash -c
        "composer install --optimize-autoloader \
        && tail -f /dev/null"
    networks:
      - php-enum

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 8080:80
    volumes:
      - .:/var/www/php-enum
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - php-enum

networks:
  php-enum:
    name: php-enum